name: Pipeline Avancée

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation des dépendances
        run: npm install
      - name: Build du code
        run: npm run build
      - name: Archive des résultats de tests
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
